import Navbar from '@/components/layout/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ShoppingCartProvider } from '@/context/ShoppingCartContext'
import ShoppingCart from '@/components/layout/ShoppingCart'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ShoppingCartProvider>
      <html lang="pt-br">
      <body className={inter.className}>
        <Navbar/>
        <ShoppingCart/>
        {children}
      </body>
    </html>
    </ShoppingCartProvider>
    
  )
}
